
export enum debugModeEnum {
    VAR_DECLARER = "VARIABLE_DECLARATION",
    OBJECT_OBSERVER = "OBJECT_OBSERVER",
    VAR_OBSERVER = "VARIABLE_OBSERVER",
    API_OVERRIDE_TRACKER = "API_OVERRIDE_TRACKER",
    API_OBSERVER = "API_OBSERVER",
};
